from __future__ import annotations

GROK_MCP_MOUNT_PATH = "/grok/mcp"
GROK_MCP_PATH = "/grok/mcp/"
GROK_OAUTH_SCOPE = "agent-call:use"
GROK_OAUTH_SUBJECT = "agent-call-owner"
GROK_OAUTH_CONSENT_PATH = "/grok/oauth/consent"
GROK_OAUTH_REVOKE_ALL_PATH = "/internal/grok-oauth/revoke-all"

ACCESS_TOKEN_TTL_MIN_SECONDS = 60
ACCESS_TOKEN_TTL_MAX_SECONDS = 3600
REFRESH_TOKEN_TTL_MIN_DAYS = 1
REFRESH_TOKEN_TTL_MAX_DAYS = 90
AUTH_CODE_TTL_MIN_SECONDS = 30
AUTH_CODE_TTL_MAX_SECONDS = 300

OWNER_SECRET_MIN_LENGTH = 16
DEPLOYMENT_SECRET_MIN_LENGTH = 32

CONSENT_BODY_MAX_BYTES = 8 * 1024
REGISTER_BODY_MAX_BYTES = 16 * 1024
FAILED_ATTEMPT_LIMIT = 5
FAILED_ATTEMPT_WINDOW_SECONDS = 15 * 60
OWNER_SECRET_RATE_LIMIT_KEY = "owner-secret"

# RFC 7636 S256: BASE64URL(SHA256(verifier)) without padding is 43 characters.
PKCE_S256_CHALLENGE_LENGTH = 43

OAUTH_CLIENT_MAX_COUNT = 64
OAUTH_CLIENT_UNUSED_RETENTION_SECONDS = 30 * 24 * 60 * 60
OAUTH_AUDIT_MAX_COUNT = 2048
OAUTH_AUDIT_RETENTION_SECONDS = 90 * 24 * 60 * 60
OAUTH_CLIENT_METADATA_MAX_JSON_BYTES = 8 * 1024
OAUTH_CLIENT_NAME_MAX_LENGTH = 128
OAUTH_CLIENT_URI_MAX_LENGTH = 2048
OAUTH_CLIENT_REDIRECT_URI_MAX_COUNT = 8
OAUTH_CLIENT_CONTACT_MAX_COUNT = 8
OAUTH_CLIENT_CONTACT_MAX_LENGTH = 254
OAUTH_CLIENT_SOFTWARE_MAX_LENGTH = 128
OAUTH_CLIENT_JWKS_MAX_JSON_BYTES = 2048
OAUTH_CLIENT_ID_MAX_LENGTH = 128
OAUTH_CLIENT_SECRET_MAX_LENGTH = 256
OAUTH_CLIENT_GRANT_TYPE_MAX_COUNT = 8
OAUTH_CLIENT_GRANT_TYPE_MAX_LENGTH = 64

GENERIC_AUTH_FAILURE = "Authorization failed."
